server:
  port: 8888

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
# 静态路由
    gateway:
      routes:
        - id: rule-user
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
            - Method=POST
#必须带上查询参数name=lili才能访问
            - Query=name,lili
#        - id: route-rule-2
#          uri: lb://role-server
#          predicates:
#            - Path=/role/*

